USE TEST;
CREATE TABLE CUSTOMER_DETAILS(
CUSTOMER_ID INT,
NAME varchar(255),
ADDRESS varchar(255),
AGE INT);

desc CUSTOMER_DETAILS;

insert INTO CUSTOMER_DETAILS(
CUSTOMER_ID,NAME,ADDRESS)values
(3,"ARIANA","MIAMI");

select * FROM CUSTOMER_DETAILS;