-- KEY 
--  UNIQUE KEY
--  NOT NULL
--  PRIMARY KEY
--  FOREIGN KEY

-- UNIQUE KEY :NO DUPLICATE ENTRY.

USE SE_4_30_TO_6;

create TABLE EMPLOYEE(
E_ID INT unique KEY,
E_NAME varchar (255),
E_SALARY INT,
E_AGE int);

DESC EMPLOYEE;
insert into EMPLOYEE(
E_NAME,E_SALARY,E_AGE)values
("JULIA",70000,25);

select * FROM EMPLOYEE;
